name: _error
timestamp: 1748586448
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1748586448
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5107: Logo
  spacer:
    spacer-4738: Spacer
    spacer-9408: Spacer
  menu:
    menu-8010: Menu
  content:
    system-content-6395: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-4216: Copyright
  branding:
    branding-9289: Branding
  mobile-menu:
    mobile-menu-5706: Mobile-menu
inherit: {  }
