name: _offline
timestamp: 1748586448
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1748586448
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-4995: Logo
  spacer:
    spacer-5105: Spacer
    spacer-3323: Spacer
  messages:
    system-messages-4931: 'System Messages'
  content:
    system-content-9740: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-5260: Copyright
  branding:
    branding-2961: Branding
inherit: {  }
